name: Mi WEB en Jekyll y Git
url: https://mi-web-personal.github.io
description: Template de Jekyll para webs en Github

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
